name: estetica_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  path: ^1.8.3
  flutter_svg: ^1.0.0 # Added flutter_svg package

  image_picker: ^1.0.4

  # Navigation
  go_router: ^10.1.2
  url_strategy: ^0.2.0

  # BLOC
  flutter_bloc: ^8.1.1
  bloc: ^8.1.1
  equatable: ^2.0.5

  #Firebase
  firebase_core: ^2.9.0
  dio: ^5.4.3+1
  google_nav_bar: ^5.0.6

  # user_repository:
  #   path: packages/user_repository
  # pizza_repository:
  #   path: packages/pizza_repository

  client_repository:
    path: packages/client_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Bold.ttf
        - asset: assets/fonts/DancingScript-Medium.ttf
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-SemiBold.ttf
