name: estetica_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  image_picker: ^1.0.4
  # Email
  mailer: ^6.1.0
  # Navigation
  google_nav_bar: ^5.0.6
  # UI
  flutter_slidable: ^3.1.0
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  # BLOC
  flutter_bloc: ^8.1.1
  bloc: ^8.1.1
  #Firebase
  firebase_core: ^2.9.0

  client_repository:
    path: packages/client_repository
  product_repository:
    path: packages/product_repository
  service_repository:
    path: packages/service_repository
  ticket_repository:
    path: packages/ticket_repository
  brand_repository:
    path: packages/brand_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Bold.ttf
        - asset: assets/fonts/DancingScript-Medium.ttf
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-SemiBold.ttf
